services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgressql/data
      - ./db-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ekod
      POSTGRES_PASSWORD: ekod
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      - DB_HOST: db
      - DB_PORT: 5432
      - DB_USER: ekod
      - DB_PASSWORD: ekod
      - DB_NAME: tasks

    volumes:
      postgres_date:
